# Generated by Django 3.1.7 on 2021-03-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testmony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='testmonies/')),
                ('product', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
